version: '3'

services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=votarr
      - POSTGRES_USER=votarr
      - POSTGRES_PASSWORD=votarr_password
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      - DATABASE_URL=postgresql://votarr:votarr_password@db/votarr
      - JWT_SECRET=your_secret_key
    ports:
      - 4000:4000
    depends_on:
      - db

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    environment:
      - VITE_API_URL=http://localhost:4000/api
    ports:
      - 3000:3000
    depends_on:
      - api

volumes:
  db-data:
